# Generated by Django 4.0.5 on 2022-06-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그'},
        ),
    ]
