# Generated by Django 4.0.5 on 2022-06-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
