# Generated by Django 4.0.5 on 2022-06-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_comment_user_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
